import type { Metadata } from "next";
import {Geist, Geist_Mono, Noto_Sans_Thai, Nunito} from "next/font/google";
import "./globals.css";

const geistSans = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
});

const geistMono = Noto_Sans_Thai({
  variable: "--font-sans-thai",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
