name: Build Standalone App

on:
  release:
    types: [published]   # runs when a release is created/published

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install Dependencies
        run: npm install

      - name: Build Next.js (Standalone Output)
        run: npm run build

      - name: Copy static files to standalone build
        run: |
          cp -r .next/static .next/standalone/.next/static

      - name: Zip standalone folder
        run: |
          cd .next
          zip -r ../standalone.zip standalone

      - name: Upload asset to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: standalone.zip
          asset_name: standalone.zip
          asset_content_type: application/zip
